config/routes.rb
Rails.application.routes.draw do
  devise_for :users
 root 'homes#top'
 get 'home/about' => 'homes#about'
 resources :users, only: [:show,:index,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
end




 resources :books do
   resource :favorites, only: [:create, :destroy]
   resources :book_comments, only: [:create, :destroy]
 end
  get '/search' => 'search#search'
  
end

app/controllers/search_controller.rb
class SearchController < ApplicationController

  def search
    @book = Book.new

    if params[:genre] == "user"
      if params[:direction] == "完全一致"
        @users = User.where(name: "#{params[:q]}")
      elsif params[:direction] == "前方一致"
        @users = User.where('name LIKE ?', "#{params[:q]}%")
      elsif params[:direction] == "後方一致"
        @users = User.where('name LIKE ?', "%#{params[:q]}")
      elsif params[:direction] == "部分一致"
        @users = User.where('name LIKE ?', "%#{params[:q]}%")
      end

    elsif params[:genre] == "book"
      if params[:direction] == "完全一致"
        @books = Book.where(title: "#{params[:q]}", body: "#{params[:q]}")
      elsif params[:direction] == "前方一致"
        @books = Book.where('title LIKE ? OR body LIKE ?', "#{params[:q]}%", "#{params[:q]}%")
      elsif params[:direction] == "後方一致"
        @books = Book.where('title LIKE ? OR body LIKE ?', "%#{params[:q]}", "#{params[:q]}%")
      elsif params[:direction] == "部分一致"
        @books = Book.where('title LIKE ? OR body LIKE ?', "%#{params[:q]}%", "%#{params[:q]}%")
      end
    end
  end

end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/search/search.html.erb
<div class="container">
 <div class="row">
  <div class="col-md-3">
   <h1>User info</h1>
   <%= render 'users/profile', user: current_user %>
   <h1>New book</h1>
   <%= render 'books/new', book: @book %>
  </div>

  <div class="col-md-8 offset-md-1">

  <% if params[:genre] == "user" %>
   <h1>Users</h1>
    <table class="table">
      <thead>
       <th></th>
       <th>image</th>
       <th>name</th>
      </thead>
      <tbody>
    <% @users.each do |user| %>
     <tr>
       <td><%= attachment_image_tag user, :profile_image, :fill, 40, 40, format:'jpeg', fallback: "no_image.jpg" %></td>
       <td><%= user.name %>
       <td><p>フォロー数 : <%= link_to user.followings.count, user_followings_path(user) %></p></td>
       <td><p>フォロワー数 : <%= link_to user.followers.count, user_followers_path(user) %></p></td>
       <td><%= render 'relationships/follow', user: user %></td>
       <td><%= link_to "Show", user_path(user.id) %></td>
     </tr>
    <% end %>

   <% elsif params[:genre] == "book" %>
    <h1>Books</h1>
     <table class="table">
      <thead>
       <th></th>
       <th>Title</th>
       <th>Opinion</th>
      </thead>
      <tbody>
    <% @books.each do |book| %>
     <tr>
       <td>
        <%= link_to user_path(book.id) do %>
        <%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, format:'jpeg', fallback: "no_image.jpg" %>
        <% end %>
       <br></td>
       <td><%= link_to book.title, book_path(book.id) %></td>
       <td><%= book.body %></td>

       <td><%= render 'favorites/favorite', book: book %></td>

       <td>コメント数: <%= book.book_comments.count %></td>
     </tr>
    <% end %>
   <% end %>
    </tbody>
   </table>
  </div>
 </div>
</div>