config/routes.rb
Rails.application.routes.draw do
  devise_for :users
 root 'homes#top'
 get 'home/about' => 'homes#about'
 resources :users, only: [:show,:index,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
end




 resources :books do
   resource :favorites, only: [:create, :destroy]
   resources :book_comments, only: [:create, :destroy]
 end
  get '/search' => 'search#search'
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  attachment :profile_image

  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followings, through: :follower, source: :followed
  has_many :followers, through: :followed, source: :follower

  validates :name, length: {maximum: 20, minimum: 2}, uniqueness: true
  validates :introduction, length: {maximum: 50}

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def follow(other_user)
    unless self == other_user
      follower.create(followed_id: other_user.id)
    end
  end

  def unfollow(other_user)
    follower.find_by(followed_id: other_user.id).destroy
  end

  def following?(other_user)
    followings.include?(other_user)
  end
  
  include JpPrefecture  #都道府県コードから都道府県名に自動で変換する。
  jp_prefecture :prefecture_code
  
  def prefecture_name #prefecture_nameで都道府県名を参照出来る様にする。例) @user.prefecture_nameで該当ユーザーの住所(都道府県)を表示出来る。
    JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
  end
  
  def prefecture_name=(prefecture_name)
    self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   before_action :authenticate_user!
   before_action :correct_user, only: [:edit,:update]
   
  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def index
    @users = User.all
    @book = Book.new
    @user = current_user
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
     redirect_to user_path(@user.id), notice: "You have updated user successfully."
    else
     render :edit
    end
     
  end
  
  private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
  
  def correct_user
    @user = User.find(params[:id])
    if @user!=current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_profile.html.erb
<table class="table">
    <tr><%= attachment_image_tag(user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %></tr>

    <tr>
        <th>name</th>
        <th><%= user.name %></th>
    </tr><br>

    <tr>
        <th>introduction</th>
        <th><%= user.introduction %></th>
    </tr>

    <tr>
        <th>follows</th>
        <th><%= link_to user.followings.count, user_followings_path(user) %></th>
    </tr>

    <tr>
        <th>followers</th>
        <th><%= link_to user.followers.count, user_followers_path(user) %></th>
    </tr>

</table>

<div class="row">
    <%= render 'relationships/follow', user: user %>
</div>
<th><%= link_to edit_user_path(user), class: 'btn btn-default w-178px' do %>
     <i class="fas fa-user-cog"></i>
    <% end %>
</th><br>

app/views/users/edit.html.erb
<div class="container">
 <div class="row">
  <div class="mx-auto">
    <h1>User info</h1>
     <%= form_with model: @user, local:true do |f| %>
      <% if @user.errors.any? %>
       <h3><%= @user.errors.count %>prohibited this obj from being saved:</h3>
        <ul>
         <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
         <% end %>
        </ul>
      <% end %>

      <p>Name</p>
      <%= f.text_field :name %>
      <p>Image</p>
      <%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %>
      <p>Introduction</p>
      <%= f.text_area :introduction %><br>
      <%= f.submit "Update User", class:"btn btn-secondary w-178px" %><br>
    <% end %>
  </div>
 </div>
</div>

app/views/users/index.html.erb
<div class="container">
 <div class="row">
  <div class="col-md-3">
   <h1>User info</h1>
   <%= render 'users/profile', user: current_user %>
   <h1>New book</h1>
   <%= render 'books/new', book: @book %>
  </div>

  <div class="col-md-8 offset-md-1">
   <h1>Users</h1>
    <table class="table">
      <thead>
       <th></th>
       <th>image</th>
       <th>name</th>
      </thead>
      <tbody>
    <% @users.each do |user| %>
     <tr>
       <td><%= attachment_image_tag user, :profile_image, :fill, 40, 40, format:'jpeg', fallback: "no_image.jpg" %></td>
       <td><%= user.name %>
       <td><p>フォロー数 : <%= link_to user.followings.count, user_followings_path(user) %></p></td>
       <td><p>フォロワー数 : <%= link_to user.followers.count, user_followers_path(user) %></p></td>
       <td><%= render 'relationships/follow', user: user %></td>
       <td><%= link_to "Show", user_path(user.id) %></td>
     </tr>
    <% end %>
    </tbody>
   </table>
  </div>
 </div>
</div>

app/views/users/show.html.erb
<p id="notice">
 <%=  notice %>
<div class="container">
 <div class="row">
  <div class="col-md-3">
   <h1>User info</h1>
    <%= render 'users/profile', user: @user %>
    <h1>New book</h1>
    <%= render 'books/new', book: @book %>
  </div>

  <div class="col-md-8 offset-md-1">
   <h1>Books</h1>
    <table class="table">
     <thead>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
    </thead>
    <tbody>
     <% @books.each do |book| %>
     <tr>
        <td>
            <%= link_to (book.user) do %>
            <%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, format:'jpeg', fallback: "no_image.jpg" %>
            <% end %>
        </td>
        <td><%= link_to book.title, book_path(book.id) %></td>
        <td><%= book.body %></td>

        <td>コメント数: <%= book.book_comments.count %></td>

     </tr>
     <% end %>
    </tbody>
   </table>
  </div>
 </div>
</div>